name: Release to Maven Central

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file from secrets
        run: |
          echo MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} >> .env
          echo MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} >> .env
          echo RICARDO_AUTH_JWT_SECRET=${{ secrets.RICARDO_AUTH_JWT_SECRET }} >> .env


      - name: Set up Java, Maven Central credentials, and GPG signing
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          server-id: central                          # must match <id> in pom.xml
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase:  ${{ secrets.GPG_PASSPHRASE }}

      - name: (Optional) List GPG keys to verify import
        run: gpg --list-secret-keys --keyid-format LONG

      - name: Deploy to Maven Central
        run: mvn -B clean deploy -Pcentral -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_TOKEN:    ${{ secrets.CENTRAL_TOKEN }}
